/**
 * Load and materialise the language-neutral conformance corpus.
 *
 * A read-only mirror of `interlock/testing/conformance.py`: the file is
 * generated by Python and replayed here. The JS side never invents an
 * expectation - it consumes the one both languages are checked against.
 *
 * The one gap the two sides cannot share is *storage*: the corpus writes bytes
 * as `{"kind":"bytes","hex":...}` (a convention a JSON file can hold), while
 * the wire carries `{"__interlock__":"bytes","b64":...}`. `materialiseModifiedResult`
 * is the JS twin of the Python helper that bridges them.
 */
import { readFileSync } from "node:fs";

import type { SensorEvent } from "../src/event.js";
import { sensorEvent } from "../src/event.js";
import { CORPUS_PATH } from "./harness.js";

export interface CorpusEvent {
  action: string;
  args: Record<string, unknown>;
  phase?: string;
  principal?: string | null;
  parent_principal?: string | null;
}

export interface Expectation {
  verdict?: string;
  reason?: string;
  policy_id?: string | null;
  attributed_to?: string | null;
  modified_args?: unknown;
  modified_result?: unknown;
  error?: string;
  note?: string;
}

export interface CorpusCase {
  name: string;
  note: string;
  event: CorpusEvent;
  expect: Expectation;
}

export interface Negative {
  name: string;
  note: string;
  kind: "frame" | "oversized";
  line?: string;
  error: string;
}

export interface Corpus {
  corpus_version: number;
  rules: string;
  cases: CorpusCase[];
  negatives: Negative[];
}

export const CORPUS: Corpus = JSON.parse(
  readFileSync(CORPUS_PATH, "utf8"),
) as Corpus;

export const CASES = CORPUS.cases;
export const NEGATIVES = CORPUS.negatives;

/** Build the event a corpus case describes. */
export function eventOf(payload: CorpusEvent): SensorEvent {
  return sensorEvent({
    action: payload.action,
    args: { ...payload.args },
    principal: payload.principal ?? null,
    parent_principal: payload.parent_principal ?? null,
    phase: payload.phase === "result" ? "result" : "call",
  });
}

/** Turn a stored expectation back into the value a caller would receive. */
export function materialiseModifiedResult(value: unknown): unknown {
  if (
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value) &&
    (value as { kind?: unknown }).kind === "bytes"
  ) {
    return Buffer.from((value as { hex: string }).hex, "hex");
  }
  return value;
}

/**
 * Structural equality over decoded wire values. Buffers compare by content,
 * arrays and objects by shape - the shapes the codec can produce.
 */
export function sameValue(a: unknown, b: unknown): boolean {
  if (Buffer.isBuffer(a) || Buffer.isBuffer(b)) {
    return Buffer.isBuffer(a) && Buffer.isBuffer(b) && a.equals(b);
  }
  if (Array.isArray(a) || Array.isArray(b)) {
    if (!Array.isArray(a) || !Array.isArray(b) || a.length !== b.length) {
      return false;
    }
    return a.every((item, index) => sameValue(item, b[index]));
  }
  if (a !== null && b !== null && typeof a === "object" && typeof b === "object") {
    const left = a as Record<string, unknown>;
    const right = b as Record<string, unknown>;
    const keys = Object.keys(left).sort();
    const other = Object.keys(right).sort();
    if (keys.length !== other.length || keys.some((key, i) => key !== other[i])) {
      return false;
    }
    return keys.every((key) => sameValue(left[key], right[key]));
  }
  return a === b;
}
